FROM docker.io/rocker/r-base:4.3.1

#Metadata
LABEL base.image="rocker/r-base:4.3.1"
LABEL version="4.3.1-TAGC"
LABEL description="R 4.3.1-TAGC"
LABEL tag="TimeAttackGenComp"

RUN install2.r --error --deps TRUE --skipinstalled \
    RColorBrewer
